networks:
  my_network:

services:
  blazorapp:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=solarmhc;User=root;Password=123456;
      - WEATHER_API=${WEATHER_API}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 80:80
    networks:
      - my_network
    restart: always

  database:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: solarmhc
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456 || exit 1"]
      interval: 10s
      retries: 5
